# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.credencial_uploader:
        class: AppBundle\FileUploader
        arguments: ['%credenciales_directory%']

    app.doctrine_credencial_listener:
        class: AppBundle\EventListener\CredencialUploadListener
        arguments: ['@app.credencial_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    app.jarvis:
        class: AppBundle\Controller\JarvisController

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]