<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends EntityRepository
{
	/**
	 * @param string $role
	 *
	 * @return array
	 */
	public function findStudentsToCreate($role = "ROLE_ESTUDIANTE")
	{
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('e')
	        ->from($this->_entityName, 'e')
	        //->from("UserBundle\Entity\Usuario", 'u')
	        ->innerJoin('e.usuario', 'u')
	        //->join('u.usuario', 'u', 'WITH', 'u.id = ?1', 'e.usuario_id')
	        ->where('u.roles LIKE :roles')
	        ->setParameter('roles', '%"'.$role.'"%');

	    return $qb;
	    /*$qb = $this->_em->createQueryBuilder();
	    $qb->select('u')
	        ->from($this->_entityName, 'u')
	        ->where('u.roles LIKE :roles')
	        ->setParameter('roles', '%"'.$role.'"%');

	    return $qb;*/
	}
}
