<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends EntityRepository
{
	/**
	 * @param string $role
	 *
	 */
	public function findStudentsToCreate($role = "ROLE_ESTUDIANTE")
	{
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('e')
	        ->from($this->_entityName, 'e')
	        ->from("UserBundle\Entity\Usuario", 'u')

	        //->where('u.roles LIKE :roles')
	        ->where($qb->expr()->andX(
                    $qb->expr()->like('u.roles', "'%".$role."%'"),
                    $qb->expr()->neq('u.id', 'e.usuario')
        ));

	    return $qb;
	}
}
