<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	
	/**
	 * @param string $role
	 *
	 * @return array
	 */
	public function findByRole($role)
	{
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('u')
	        ->from($this->_entityName, 'u')
	        ->from("UserBundle\Entity\Estudiante", 'e')
	        ->where('u.roles LIKE :roles')
	        ->setParameter('roles', '%"'.$role.'"%');

	    return $qb;
	}
}
